language: go

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          packages:
          - cmake
          - pkg-config
          - shellcheck
    - os: osx
      osx_image: xcode8.1
      before_script:
        - brew install shellcheck

script:
  - shellcheck build.sh
  - ./build.sh
  - go test $(glide nv)
