language: go

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      install:
        - sudo sh -c 'echo "deb http://archive.ubuntu.com/ubuntu/ xenial main restricted universe" >> /etc/apt/sources.list'
        - sudo apt-get update -qq
        - sudo apt-get install -y pkg-config cmake shellcheck
    - os: osx
      osx_image: xcode8.1
      install:
        - brew install pkg-config cmake shellcheck glide

script:
  - shellcheck build.sh
  - ./build.sh

addons:
  artifacts:
    s3_region: "us-gov-west-1" # defaults to "us-east-1"
    paths: $(ls releases/git-seekret-* | tr "\n" ":")

# before_deploy:
#   - export RELEASE_FILE=$(ls releases/git-seekret-*)

# deploy:
#   provider: releases
#   api_key: GITHUB_API_KEY_GOES_HERE
#   file_glob: true
#   file: "${RELEASE_FILE}"
#   skip_cleanup: true
#   overwrite: true
#   on:
#     tags: true
