language: go

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.2

before_install:
  - sudo sh -c 'echo "deb http://archive.ubuntu.com/ubuntu/ xenial main restricted universe" >> /etc/apt/sources.list'
  - sudo add-apt-repository ppa:masterminds/glide -y
  - sudo apt-get update
  - sudo apt-get install -y pkg-config libgit2-dev
  - sudo apt-get install glide
  - sudo apt-get clean

install:
  - glide install
  - go build

script:
  - go test $(glide nv)
  - ./build.sh
