language: go

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      before_install:
        - sudo sh -c 'echo "deb http://archive.ubuntu.com/ubuntu/ xenial main restricted universe" >> /etc/apt/sources.list'
        - sudo apt-get update -qq
        - sudo apt-get install -y pkg-config libgit2-dev cmake shellcheck
    - os: osx
      osx_image: xcode8.1
      before_install:
        - brew install pkg-config libgit2 cmake shellcheck glide

install:
  - shellcheck build.sh
  - ./build.sh

script:
  - ./releases/git-seekret-*
  - go test -tags static $(glide nv)

# before_deploy:
#   - export RELEASE_FILE=$(ls releases/git-seekret-*)

# deploy:
#   provider: releases
#   api_key: GITHUB_API_KEY_GOES_HERE
#   file_glob: true
#   file: "${RELEASE_FILE}"
#   skip_cleanup: true
#   overwrite: true
#   on:
#     tags: true