language: go

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      before_install:
        - sudo sh -c 'echo "deb http://archive.ubuntu.com/ubuntu/ xenial main restricted universe" >> /etc/apt/sources.list'
        - sudo apt-get update -qq
        - sudo apt-get install -y pkg-config libgit2-dev cmake shellcheck
      before_script:
        - sudo apt-get remove -y libgit2-*
    - os: osx
      osx_image: xcode8.1
      before_install:
        - brew install shellcheck
        - brew install libgit2
      before_script:
        - brew uninstall libgit2

script:
  - shellcheck build.sh
  - ./build.sh
  - go test $(glide nv)
